### ISSUE TITLE
augment() not working on data frame made by dplyr(use of do(nlme))

### ISSUE THREAD

**Issue by MunjalP** [tidyverse/broom#116]
Hi.I am new to git hub but i am an intermediate R user.I am trying to fit the nlme model fit to data frame by group.[ using dplyr>do(nlme(model)) ].

`library(dplyr);library(tidyr);
library(broom);library(nlme)`

`stacked.nlme.objects` `<- Boot.data.frame %>%`
                                          `group_by(sample)%>%`
                                          `do(model.fits=nlme(response~derive(P1,P2,P3,independent variable),`
                                                                           `data=.,`
                                                                            `fixed=P1+P2+P3~1,`
                                                                            `random=P1~1|subject,`
                                                                            `na.action=na.omit,`
                                                                            `method="REML" ))`

stacked.nlme.objects is the data.frame with two variables. 1)sample 2)model.fits
where model.fits come out to be vector of list (nlme objects).

I want to now extract the .resid,.fitted etc columns (like broom package ) on this data frame but it doesnt work.
I have tried the following already.

`Predictions.df <- augment(stacked.nlme.objects,Boot.data.frame)`

Can you please help me out in this ?

Thank you !

**Comment by alexpghayes** [comment]
This is some very late assistant, but the current suggested approach is to use the `rsample` package in conjunction with `purrr::map` and `tidyr::unnest` like so:

```r
library(tidyverse)
library(lme4)

fit_lme_model <- function(split) {
  lmer(Sepal.Width ~ Sepal.Length + (1 | Species),
       data = rsample::analysis(split))
}

boots <- rsample::bootstraps(iris)

boots %>% 
  mutate(model = map(splits, fit_lme_model),
         augmented = map(model, augment)) %>% 
  unnest(augmented)
#> Warning: package 'bindrcpp' was built under R version 3.4.4
#> # A tibble: 3,750 x 14
#>    id    .rownames Sepal.Width Sepal.Length Species .fitted  .resid .fixed
#>    <chr> <chr>           <dbl>        <dbl> <fct>     <dbl>   <dbl>  <dbl>
#>  1 Boot~ 104               2.9          6.3 virgin~    2.87  0.0268   3.19
#>  2 Boot~ 119               2.6          7.7 virgin~    3.27 -0.669    3.58
#>  3 Boot~ 68                2.7          5.8 versic~    2.72 -0.0190   3.05
#>  4 Boot~ 89                3            5.6 versic~    2.66  0.338    2.99
#>  5 Boot~ 78                3            6.7 versic~    2.97  0.0263   3.30
#>  6 Boot~ 43                3.2          4.4 setosa     3.29 -0.0886   2.65
#>  7 Boot~ 55                2.8          6.5 versic~    2.92 -0.117    3.24
#>  8 Boot~ 99                2.5          5.1 versic~    2.52 -0.0209   2.85
#>  9 Boot~ 53                3.1          6.9 versic~    3.03  0.0697   3.36
#> 10 Boot~ 47                3.8          5.1 setosa     3.49  0.313    2.85
#> # ... with 3,740 more rows, and 6 more variables: .mu <dbl>,
#> #   .offset <dbl>, .sqrtXwt <dbl>, .sqrtrwt <dbl>, .weights <dbl>,
#> #   .wtres <dbl>
```

Also check out [the bootstrapping vignette](http://broom.tidyverse.org/articles/bootstrapping.html), which has been updated to match this workflow.
