### ISSUE TITLE
Would be nice for augment() to augment a .index variable

### ISSUE THREAD

**Issue by DarrenBishop** [tidyverse/broom#117]
A .index (dot index) variable would simply contain the row index; other suggested names '.n', '.row'

This would be useful in plotting residuals against the index to detect patterns and therefore reflecting missing or un-captured regressors when doing exploratory analysis

**Comment by alexpghayes** [comment]
I think this is a task best left to `dplyr` for after the fact:

```r
library(dplyr)

broom::tidy(lm(hp ~ ., mtcars)) %>% 
  mutate(.index = row_number())
```

Let me know if there's a workflow where this is particularly cumbersome and we could potentially revisit this then?
