### ISSUE TITLE
error object 'fstatistic' not found in glance(lm(model))

### ISSUE THREAD

**Issue by RMHogervorst** [tidyverse/broom#134]
https://stackoverflow.com/questions/31818475/broom-dplyr-error-with-glance-when-using-lm-instead-of-biglm

I'm experiencing similar problems to this. 

When I use glance on a lm object that is not working:

```
summary(file$model[[2]])
Call:
lm(formula = cumects ~ Datum.beoordeling, data = .)

Residuals:
ALL 1 residuals are 0: no residual degrees of freedom!

Coefficients: (1 not defined because of singularities)
                  Estimate Std. Error t value Pr(>|t|)
(Intercept)              5         NA      NA       NA
Datum.beoordeling       NA         NA      NA       NA

Residual standard error: NaN on 0 degrees of freedom
```

I get the result:

```
broom::glance(file$model[[2]])
Error in data.frame(r.squared = r.squared, adj.r.squared = adj.r.squared,  : 
  object 'fstatistic' not found
```

It would be nicer if a NA was produced I think?

**Comment by bschneidr** [comment]
This issue also appears when you use an intercept-only linear model.

You can reproduce the error with the following code:

    my_data <- data_frame(x = rnorm(100),
                          y = x^2 + rnorm(100))

    my_model <- lm(data = my_data, formula = "y ~ 1")
    glance(my_model)

Here, the call to `glance()` generates the following error:

    Error in data.frame(r.squared = r.squared, adj.r.squared = adj.r.squared,  : 
    object 'fstatistic' not found

It would make more sense for `glance()` to simply return an `NA` for the fstatistic in such a case, as @RMHogervorst suggested.

**Comment by palfalvi** [comment]
I solved this problem just with removal sd = 0 datasets from the data.

Using the data on [David Robinsons' blogpost](http://varianceexplained.org/r/tidy-genomics-broom/) and fitting regression for every group

This will produce the same error (if you proceed to have cleaned_data)

```r
lm_nutrient <- function(df){ lm(data = df, formula = expression ~ rate)}

lin_mods <- cleaned_data %>%
  group_by(name, systematic_name, nutrient) %>%
  nest() %>%
  mutate(
   lm = data %>% map(lm_nutrient),
   glance = lm %>% map(broom::glance),
   r_sqrt = glance %>% map_dbl("r.squared"),
   tidy = lm %>% map(broom::tidy),
   augment = lm %>% map(broom::augment)
  )
```

But if you put 4 extra line for filtering, it will work (but there will be one filtered line!)

```r
lm_nutrient <- function(df){ lm(data = df, formula = expression ~ rate)}
sd_filter <- function(df){ sd(df$expression) }

lin_mods <- cleaned_data %>%
  group_by(name, systematic_name, nutrient) %>%
  nest() %>%
  mutate(filter = data %>% map_dbl(sd_filter)) %>%
  filter( filter != 0) %>%
  select(-filter) %>%
  mutate(
   lm = data %>% map(lm_nutrient),
   glance = lm %>% map(broom::glance),
   r_sqrt = glance %>% map_dbl("r.squared"),
   tidy = lm %>% map(broom::tidy),
   augment = lm %>% map(broom::augment)
  )
```

I hope it will be fixed to give back NAs, it is a little inconvenient to care manually about this every time.

**Comment by alexpghayes** [comment]
At some point this got taken care apparently!

```r
y <- rnorm(100)
m <- lm(y ~ 1)
broom::glance(m)
#>   r.squared adj.r.squared     sigma statistic p.value df    logLik
#> 1         0             0 0.9558854        NA      NA  1 -136.8796
#>        AIC      BIC deviance df.residual
#> 1 277.7592 282.9696 90.45797          99
```
