### ISSUE TITLE
Proposal of tidiers for chisq.test

### ISSUE THREAD

**Issue by larmarange** [tidyverse/broom#136]
For personal need, I developed a `tidy_chisq` function for tidying the result of a chi-squared test and obtaining the detail of each cell.

``` r
test <- chisq.test(xtabs(Freq ~ Sex + Class, data = as.data.frame(Titanic)))
tidy_chisq(test)
```

produces

```
     Sex Class observed       prop   row.prop  col.prop  expected  residuals     stdres
1   Male   1st      180 0.08178101 0.10398614 0.5538462 255.59973  -4.728681 -11.083954
2 Female   1st      145 0.06587915 0.30851064 0.4461538  69.40027   9.074854  11.083954
3   Male   2nd      179 0.08132667 0.10340843 0.6280702 224.14130  -3.015179  -6.993369
4 Female   2nd      106 0.04815993 0.22553191 0.3719298  60.85870   5.786457   6.993369
5   Male   3rd      510 0.23171286 0.29462738 0.7223796 555.24125  -1.919967  -5.041320
6 Female   3rd      196 0.08905043 0.41702128 0.2776204 150.75875   3.684626   5.041320
7   Male  Crew      862 0.39164016 0.49797805 0.9740113 696.01772   6.291462  17.607380
8 Female  Crew       23 0.01044980 0.04893617 0.0259887 188.98228 -12.074000 -17.607380
```

This function is also compatible with the result of `svychisq` from `survey` package. The code could be seen at https://github.com/larmarange/JLutils/blob/master/R/tidy_chisq.R

First question: do you think that such function would be relevant for `broom`? If yes, I will prepare a pull request.

Second question: how should it be integrated in `broom`? 

Basically, I can see two potential ways, considering that the result of `chisq.test` is of class `htest`.
1. for `htest` objects, a test will look at the presence of `observed`, `expected`, `residuals` and `stdres`. In such case, `tidy` will produce the result of `tidy_chisq` while `glance` output will remain unchanged (Note: so far, `tidy` and `glance` produce the same output for `htest` objects).
2. we could consider that in fact such results are more relevant for `table` objects. Therefore, the idea would be to extend the `tidy.table` function and, in the case 2 dimension table, to perform a chi-squared test and add the additional columns to the output. However, it would require to also create a `tidy.svytable` method for the particular case of tables produced with the `survey` package in order to compute an appropriate chi-squared test taking into account the survey design.

Best regards

**Comment by nutterb** [comment]
This seems more like an `augment` method than a tidier.  But still has the difficulty of knowing what to do with differing forms of `htest` objects. If I were to do it, I would write an `augment.htest` method with unexpired sub functions for different forms, so long as there is a consensus of what is useful augmented returns.

**Comment by larmarange** [comment]
You are right @nutterb it's maybe more appropriate as an `augment` method if we consider that the original data of a chi-squared test is the table provided to the `chisq.test` function, rather than the data.frame used to produce that table.

So far, no `augment` method exists for `htest` object. However, I am not sure yet that could be the output for other type of htest.

**Comment by nutterb** [comment]
If I were to do it, I'd go about it like this:

```r
library(broom)

augment.htest <- function(x, ...)
{
  switch(x$method,
         "Pearson's Chi-squared test" = augment_chisq_test(x, ...),
         stop("augment doesn't know how to deal with class htest with method '",
              x$method, "'")
  )
}

augment_chisq_test <- function(x, ...) {
  d <- length(dimnames(as.table(x$observed)))
  ret <- as.data.frame(as.table(x$observed))
  names(ret)[d+1] <- "observed"
  
  ret <- cbind(ret, prop = as.data.frame(prop.table(as.table(x$observed)))[[d+1]])
  if (d == 2) {
    ret <- cbind(ret, row.prop = as.data.frame(prop.table(as.table(x$observed), 1))[[d+1]])
    ret <- cbind(ret, col.prop = as.data.frame(prop.table(as.table(x$observed), 2))[[d+1]])
  }
  
  ret <- cbind(ret, expected = as.data.frame(as.table(x$expected))[[d+1]])
  ret <- cbind(ret, residuals = as.data.frame(as.table(x$residuals))[[d+1]])
  ret <- cbind(ret, stdres = as.data.frame(as.table(x$stdres))[[d+1]])
  ret
}

test <- chisq.test(xtabs(Freq ~ Sex + Class, data = as.data.frame(Titanic)))
augment(test)
```

additional `augment_t_test` type methods could be added if/when anyone every decided on a coherent format for the `augment`.

**Comment by larmarange** [comment]
Thanks @nutterb 

I will prepare a pull request accordingly

**Comment by larmarange** [comment]
I have prepared a pull request.

Please note that the augment method tests the presence of the elements `c("observed", "expected", "residuals", "stdres")` in the `htest` object. It allows to detect all chi-squared tests outputs (including outputs from `svychisq`) while the `method` element is varying according to the type pf chi-squared test.
