### ISSUE TITLE
support for rpart and randomforest models?

### ISSUE THREAD

**Issue by beanumber** [tidyverse/broom#153]
I haven't thought this through, but here are some initial ideas for `mod <- rpart()`:
- `tidy()` would want to be some combination of `mod$frame` and `mod$split`, methinks. Similar to the output of `summary.rpart()` but as a `data.frame`
- `augment()` includes the `.fitted` value
- `glance()` displays the confusion matrix and overall accuracy

**Comment by mdlincoln** [comment]
I'm taking a whack at writing implementations for randomForest models now. Still a WIP, but I hope to have it cleaned up later this week: https://github.com/mdlincoln/broom/tree/randomForest

**Comment by alexpghayes** [comment]
Closing this since development of tree based tidiers has now moved to [`broomstick`](https://github.com/njtierney/broomstick). Interested parties stay tuned for the "what tidiers should live where" discussion later in the summer.
