### ISSUE TITLE
Compatibility with Ordinal package

### ISSUE THREAD

**Issue by roxannebeauclair** [tidyverse/broom#156]
Hi,

This is just a suggestion: but could you potentially make broom compatible with different classes of models produced through the Ordinal package? For example, clm, clmm, clm2, clmm2?

Thanks for your time and consideration.
Roxy

**Comment by larmarange** [comment]
For information, there is already a tidy method developed for clm objects: https://github.com/dnbarron/tidyclm

**Comment by alexpghayes** [comment]
Closing in favor of #292 and the potentially PR from that.

**Comment by alexpghayes** [comment]
Merged! You can either use the dev version and install from github or wait for the `broom 0.5.0` release in early July.

Thanks @larmarange yet again!
