### ISSUE TITLE
Compatibility with mgcv package

### ISSUE THREAD

**Issue by roxannebeauclair** [tidyverse/broom#169]
Greetings,

I see that broom is compatible with the gam package. Is it possible to also do so with the mgcv package for generalised additive models?

Warm regards,
Roxy

**Comment by adibender** [comment]
There is support for mgcv gam objects. Did you try the newest version of broom?

**Comment by adibender** [comment]
I was mistaken, the functions work in some situations, because the objects returned from `mgcv::gam` functions are of class `gam`, which is also true for objects returned by the `gam::gam´.

**Comment by alexpghayes** [comment]
This got added at some point!

```r
m <- mgcv::gam(mpg ~ s(hp), data = mtcars)
broom::tidy(m)
#> Warning: package 'bindrcpp' was built under R version 3.4.4
#>    term      edf   ref.df statistic      p.value
#> 1 s(hp) 2.618499 3.262509  26.25636 2.289197e-10
```
