### ISSUE TITLE
Error when tidying lsmeans::contrast

### ISSUE THREAD

**Issue by puterleat** [tidyverse/broom#179]
This is a minimal example of the problem (requires dplyr):

```
data_frame(y=rnorm(100), x=rep(c("Single", "Double-Barrelled"), 50)) %>% 
  lm(y~x, data=.) %>% lsmeans::lsmeans(., ~x) %>% lsmeans::contrast(., "pairwise") %>% tidy

```

Because of the hyphen in the x factor levels it outputs:

```
 level1    level2     estimate   std.error   df   statistic   p.value 
-------- ----------- ---------- ----------- ---- ----------- ---------
 Double   Barrelled    -0.01       0.18      98     -0.07      0.94   

```

But should output

```
 level1            level2     ...
------------------ ----------- ...
 Double-Barrelled    Single     ...
```

**Comment by alexpghayes** [comment]
Boils down to a regex issue in `tidy_emmeans` I believe. On the docket.

**Comment by bmannakee** [comment]
The regex works, changing sep="-" to sep=" - " in the call to solves this. 

data_frame(y = rnorm(100), x = rep(c("Single", "Double-Barrelled"), 50)) %>% 
  lm(y ~ x, data = .) %>% lsmeans::lsmeans(., ~x) %>% lsmeans::contrast(., 
  "pairwise") %>% tidy %>% print()
#>             level1 level2  estimate std.error df statistic   p.value
#> 1 Double-Barrelled Single 0.3101729 0.1975202 98  1.570335 0.1195605

I can do a pull request if you would like. Does this need a test?

**Comment by alexpghayes** [comment]
Yeah, that'd be great. Definitely needs a test. Thanks!
