### ISSUE TITLE
Tidy multinom objects when formula in a string

### ISSUE THREAD

**Issue by thomasjwood** [tidyverse/broom#184]
Tidying `nnet::multinom` objects seems to fail when the formula is provided as string. 

    library(plyr)
    library(tidyverse)
    library(nnet)

    data(mtcars)

    lf <- str_c("cyl ~ ",
          c("mpg",
            "hp",
            "wt"))

    lf %>%
      llply(function(i)
        i %>% 
          multinom(data = mtcars))

works fine, but this:
    
     lf %>%
      llply(function(i)
        i %>% 
          multinom(data = mtcars) %>%
          tidy)

results in:
      
     Error: object of type 'closure' is not subsettable 

but this:

    multinom(cyl ~ mpg, data = mtcars) %>%
    tidy

works.

**Comment by nutterb** [comment]
This isn't really an issue with `tidy`.  Observe:

```r
lf %>%
  llply(function(i)
    i %>% 
      multinom(data = mtcars) %>%
      summary())
```

Results in the same error.  `tidy.multinom` uses the `summary.multinom` method, which is why you see the error when running `tidy`.  

You can get the intended result by making the string a formula before you pass it to `multinom`.

```r
lf %>%
  llply(function(i)
    as.formula(i) %>% 
      multinom(data = mtcars) %>%
      tidy())
```

**Comment by alexpghayes** [comment]
Closing this since it isn't `broom` related.
