### ISSUE TITLE
Suggestion: additional a column in the glance function

### ISSUE THREAD

**Issue by pbiecek** [tidyverse/broom#189]
Shall the glance function returns a column 'model' with the class of model being processed (lm/glm/coxph)?
Otherwise it is hard to guess what kind of model is processed.

**Comment by pbiecek** [comment]
Also it may be beneficial to add a column with model formula to the glance() function (where it is applicable).

**Comment by alexpghayes** [comment]
At the moment the philosophy is that `glance` shouldn't contain information from the original function call (i.e. arguments passed to a modelling function, or the name of the function itself).

If you have some example use cases where this would be valuable we may be able to suggest some alternatives.
