### ISSUE TITLE
tidy.survfit is broken for multi-state models

### ISSUE THREAD

**Issue by jwdink** [tidyverse/broom#193]
This appears to be caused by: https://github.com/therneau/survival/commit/22fbb2e8cb18dd3f23472652116b283ee32a722c

Working on a PR.

**Comment by jwdink** [comment]
Whoops, something is just wrong with my install-- apologies.

**Comment by dgrtwo** [comment]
This may (I'm not certain) be an issue with broom CRAN being out of date relative to GitHub. It is being resubmitted today.

Cheers!

**Comment by jwdink** [comment]
Yep, you're absolutely right.
