### ISSUE TITLE
augment.felm can't handle saved formulas [feature request]

### ISSUE THREAD

**Issue by karldw** [tidyverse/broom#211]
I'd like to save a formula as an R variable so I can use it multiple times with different data, calling `augment` for each.  That approach works with basic `lm`, but not with `felm`, erroring out on [`x$call$formula[[2]]`](https://github.com/tidyverse/broom/blob/b0b6f3ce9aadb4a2fe3215f3f0a41b253a30e6eb/R/felm_tidiers.R#L124) because the formula-as-variable can't be subset like that.

Example:
```r
library(broom)
library(lfe)

my_formula <- mpg ~ cyl
augment(felm(mpg ~ cyl, mtcars))   # works
augment(lm(my_formula, mtcars))    # works
augment(felm(my_formula, mtcars))  # fails

```

One approach to `augment.felm` could be the following, but it seems pretty dirty. Is there's a better way?
```r
if (typeof(x$call$formula) == 'language') {
    # current approach:
    y_varname <- x$call$formula[[2]]
} else {
    # handle formula in variable:
    y_varname <- get(as.character(x$call$formula))[[2]]
}
y <- eval(y_varname, envir = data)

```

**Comment by alexpghayes** [comment]
Haven't tested but pretty sure `model.response` is the appropriate way to deal with this.

```r
library(broom)
library(lfe)

my_formula <- mpg ~ cyl
m1 <- felm(my_formula, mtcars)

m2 <- felm(mpg ~ cyl, mtcars)

augment(m1) # sad
augment(m2) # happy

# what augment currently does
y <- eval(m1$call$formula[[2]], envir = data) # explodes

# pretty sure this should do it
y <- model.response(model.frame(m1))
```

**Comment by shreyas-singh-298** [comment]
I would like to fix this bug. Could you please guide me?

**Comment by alexpghayes** [comment]
Sounds good! You'll want to start by forking the broom repository, and then cloning it to your computer. Once you have it on your local computer, you should look at the `tidy.felm` function in `R/felm_tidiers.R`. My suspicion is that all you need to do to fix the bug above is replace one line (see my comment above). While you're at it, you should change `tidy.felm` to return a tibble.

After you've get the function working the way you want, the next step will be to [write some tests](http://r-pkgs.had.co.nz/tests.html) to make sure you've actually fixed the bug. In this case you can use the reprex above to add a new test in `tests/testthat/test-felm.R`.

Once the tests are passing, the final step is to commit all your work to your fork, and then open a pull request to `broom`.

A good general reference is Hadley Wickham's book R Packages, which I've linked to above. It's easy to get information overload, so just drop me a question anytime!

**Comment by ShreyasSingh** [comment]
I have pushed the changes and  created a PR. Please review
