### ISSUE TITLE
Inconsistencies in arguments for tidy.coxph

### ISSUE THREAD

**Issue by larmarange** [tidyverse/broom#219]
While most `tidy` methods are using `conf.int` as TRUE/FALSE and `conf.level` to indicate the level of confidence intervals, the `tidy.coxph` method use `conf.int` to indicate the level of confidence intervals, creating some bugs for generic functions based on `tidy`, see for example https://github.com/ggobi/ggally/blob/master/R/ggcoef.R

Shoudl `tidy.coxph` be harmonized with other methods?

**Comment by strengejacke** [comment]
Yes, this is really a strange behaviour, which prevents a generic use of `tidy()`...
