### ISSUE TITLE
How to deal with error in regression of a subgrup?

### ISSUE THREAD

**Issue by lucasmation** [tidyverse/broom#224]
Asked in  [this StackOverflow question](http://stackoverflow.com/questions/43943171/broom-regressions-for-subgroups-how-to-deal-with-error-in-reg-a-subgrup)

In a workflow of: 

```
my_data %>% group_by(my_groups) %>% 
    do(tidy(lm( my_regression, data=.) 
            ))
```

It will be fairly common for the regression to fail for some subgroup. Broom should provide a simple way to deal with such erros

**Comment by dgrtwo** [comment]
I don't think this is a problem broom should solve (any more than other functions that could surround an operation that fails); it should be handled with the purrr package (see [Dealing with failure](http://r4ds.had.co.nz/lists.html) here):

    library(purrr)
    tidy_safe <- possibly(tidy, data.frame())

    my_data %>% group_by(my_groups) %>% 
    do(tidy_safe(lm( my_regression, data=.) 
            ))

If broom always caught errors (for example, by returning an empty data frame in such cases) it would lead to confusing behavior for anyone who ran into an error on a single regression.
