### ISSUE TITLE
augment returns error when working with tbl_sql (dbplyr) objects

### ISSUE THREAD

**Issue by karpatit** [tidyverse/broom#225]
Hi,  I'm having problems when trying to generate predictions on models and data created as pointers to tables on MS SQL Server.
An example code is:

> dat1 <- tbl(con, "mytable")
> mod <- glm(outcome ~ age + sex + bmi, data=dat1, family="binomial")
> summary(mod)
> head(augment(mod))

Up to this point this works smoothly. Now, when trying to get the predictions I get errors:
> pred <- augment(mod, newdata=dat1, type="response")

```
Error in if (is.null(na_action) || nrow(original) == nrow(ret)) { : 
missing value where TRUE/FALSE needed

```
If I run this but passing the table as a data.frame it works:
> pred <- augment(mod, newdata=data.frame(dat1), type="response")

The problem is that I loss the advantage of working on the SQL Server table because the predictions are saved on the local memory. 

Is there a way to solve this issue?

**Comment by alexpghayes** [comment]
Working with data bases is unfortunately outside the current scope of `broom`. However, [`tidypredict`](http://tidypredict.netlify.com/articles/glm/) does this!
