### ISSUE TITLE
zero p values when doing t.test on grouped data

### ISSUE THREAD

**Issue by avivbd** [tidyverse/broom#227]
Not sure if this has been raised before (I'm sure someone will point it out to me if it has), but when doing a t-test on grouped data using the tidy command I get zero p-values, though when I run the tests using tapply I get p-values smaller than machine epsilon (as they should be). 

Example: 

 forg2 %>% group_by(AgeBin) %>% do(tidy(t.test(.$forg)))
Source: local data frame [4 x 9]
Groups: AgeBin [4]

      AgeBin  estimate  statistic       p.value parameter   conf.low conf.high            method
      <fctr>     <dbl>      <dbl>         <dbl>     <dbl>      <dbl>     <dbl>            <fctr>
1    [1.5,2] 0.1465688  55.248744  0.000000e+00      4999 0.14136795 0.1517696 One Sample t-test
2   (2,2.45] 0.2209216 107.107159  0.000000e+00      4999 0.21687794 0.2249652 One Sample t-test
3 (2.45,2.8] 0.1084491   5.102658  3.473174e-07      4997 0.06678303 0.1501152 One Sample t-test
4    (2.8,4] 0.1631581  33.197954 1.437898e-218      4998 0.15352310 0.1727930 One Sample t-test
 ... with 1 more variables: alternative <fctr>

Notice the zero p values. 

Now use tapply:

> tapply(forg2$forg, forg2$AgeBin, t.test)
$`[1.5,2]`

	One Sample t-test

data:  X[[i]]
t = 55.249, df = 4999, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.1413679 0.1517696
sample estimates:
mean of x 
0.1465688 

$`(2,2.45]`

	One Sample t-test

data:  X[[i]]
t = 107.11, df = 4999, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.2168779 0.2249652
sample estimates:
mean of x 
0.2209216 

$`(2.45,2.8]`

	One Sample t-test

data:  X[[i]]
t = 5.1027, df = 4997, p-value = 3.473e-07
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.06678303 0.15011525
sample estimates:
mean of x 
0.1084491 

$`(2.8,4]`

	One Sample t-test

data:  X[[i]]
t = 33.198, df = 4998, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.1535231 0.1727930
sample estimates:
mean of x 
0.1631581

Edit: this is what the data looks like:
> forg2 %>% head(20)
         forg       AgeBin
1   0.1108545 [1.5,2]
2   0.2219020 [1.5,2]
3   0.1726190 [1.5,2]
4   0.2028986 [1.5,2]
5   0.1445783 [1.5,2]
6   0.1647399 [1.5,2]
7   0.1688312 [1.5,2]
8   0.2418773 [1.5,2]
9   0.1482650 [1.5,2]
10  0.1666667 [1.5,2]
11  0.1611842 [1.5,2]
12  0.1855204 [1.5,2]
13  0.4370370 [1.5,2]
14  0.1641337 [1.5,2]
15  0.2500000 [1.5,2]
16 -0.1000000 [1.5,2]
17  0.1697417 [1.5,2]
18  0.1111111 [1.5,2]
19  0.5118110 [1.5,2]
20  0.1488673 [1.5,2]

So some (not all) of the p values that are less than machine eps show up as 0.

**Comment by bbolker** [comment]
It would be immensely useful to have a reproducible example.

**Comment by avivbd** [comment]
Sure. Let me see if I can conjure something up.

**Comment by avivbd** [comment]
library(broom) 
    library(magrittr) 
    library(dplyr) 

    set.seed(1980)
    n=1e3
    t = seq(from = 0,to = n, length.out = n+1)
    x1 = rnorm(n = n, mean = 209, sd = 10)
    df = matrix(cbind(t, x1), ncol = 2, dimnames = list(NULL, c('t', 'x1')) ) %>% data.frame()
    df$bins = cut(df$t, breaks = seq(0, n, 250), include.lowest = TRUE)

Data looks like:
    
    > df %>% head
      t       x1    bins
    1 0 200.5963 [0,250]
    2 1 208.7411 [0,250]
    3 2 200.1264 [0,250]
    4 3 210.4082 [0,250]
    5 4 209.2891 [0,250]
    6 5 197.0879 [0,250]

With broom (note the p-values):

    df %>% group_by(bins) %>% do(tidy(t.test(.$x1)))

             bins estimate statistic       p.value parameter conf.low conf.high
       <fctr>    <dbl>     <dbl>         <dbl>     <dbl>    <dbl>     <dbl>
    1     [0,250] 209.1669  306.0810  0.000000e+00       250 207.8211  210.5128
    2   (250,500] 208.1018  307.8976 1.976263e-323       249 206.7706  209.4330
    3   (500,750] 207.9229  301.8349 2.628429e-321       249 206.5661  209.2796
    4 (750,1e+03] 208.6934  345.9499  0.000000e+00       249 207.5053  209.8815
    # ... with 2 more variables: method <fctr>, alternative <fctr>

With apply:

    tapply(df$x1, df$bin, t.test)

    $`[0,250]`
    One Sample t-test
    data:  X[[i]]
    t = 306.08, df = 250, p-value < 2.2e-16
    alternative hypothesis: true mean is not equal to 0
    95 percent confidence interval:
    207.8211 210.5128
    sample estimates:
    mean of x 
    209.1669  

With a bit more thought I don't think that zero p-values are a bug. I'm guessing that the numeric values are simply the output of t.test and at some point R rounds down to zero very small numbers. However, I will say that I was confused as hell by the zero p-values in the beginning, especially when running t.test via apply gave me something different. If it pleases the authors, in my two cents it would be nicer to preserve t.test's `p-value < 2.2e-16` for very small p-values.

**Comment by dgrtwo** [comment]
This isn't related to broom: as you guessed the output of `t.test` returns a p-value of zero.

The reason we can't keep `p-value < 2.2e-16` in the output is that that would mean we'd need a character output rather than a numeric one, which prevents any further programming with it. For example, suppose your next step were to filter for tests with `p.value < .05`, or to sort in ascending order of p-values. Having a character output would break that functionality.

**Comment by bbolker** [comment]
Not that I think it's worth the considerable trouble, but *in principle* it would be possible to make `tidy()` return its own class that extended `data.frame` or `tibble` and had a custom print method ...
