### ISSUE TITLE
augment and sandwich vcov?

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/broom#237]
Hello,

Thanks for this life-saving package! I have some trouble understanding which `se.fit` are reported with `augment`. 

In my regression model, I use robust standard error in the usual way

```
ols = lm(formula, data = data)
coef = lmtest::coeftest(ols, vcov = sandwich::vcovHC(ols, "HC1"))
```

but `augment` only takes as input the `ols` object. Hence I presume it computes standard errors for the predictions under homoskedasticity only? Is that correct? How can I change that?

Thanks!

**Comment by alexpghayes** [comment]
That's correct, here `augment` doesn't have access to `coef` and computes homoskedastic errors.

My recommendation is to use the awesome `estimatr::lm_robust` function. It only has a `tidy` method at the moment but the developers (cc @lukesonnet) might be willing to add an `augment.lm_robust` method.

```r
library(estimatr)

m <- lm_robust(Sepal.Length ~ Species + Sepal.Width, iris)
tidy(m)
#>                term  estimate  std.error      p.value  ci.lower ci.upper
#> 1       (Intercept) 2.2513932 0.36968037 9.510256e-09 1.5207770 2.982009
#> 2 Speciesversicolor 1.4587431 0.10008816 2.870045e-30 1.2609343 1.656552
#> 3  Speciesvirginica 1.9468166 0.09254603 4.842545e-46 1.7639137 2.129720
#> 4       Sepal.Width 0.8035609 0.10693886 5.290510e-12 0.5922127 1.014909
#>    df      outcome
#> 1 146 Sepal.Length
#> 2 146 Sepal.Length
#> 3 146 Sepal.Length
#> 4 146 Sepal.Length
augment(m)
#> Error in augment(m): could not find function "augment"
```

**Comment by alexpghayes** [comment]
It [looks like](https://stats.stackexchange.com/questions/175127/prediction-intervals-with-heteroscedasticity) there isn't actually a meaningful way to define `.se.fit` in this context unless you make some assumptions about the nature of the heteroscedasticity. Closing since this is outside the scope of broom.

**Comment by lukesonnet** [comment]
We could consider adding something like `augment` but it won't be a top priority.

Should mention to @randomgambit that you can get the HC1 errors instead of the default HC2 errors in estimatr like so:

`estimatr::lm_robust(Sepal.Length ~ Species + Sepal.Width, iris, se_type = "HC1")`
