### ISSUE TITLE
Suggestion to create a `pkgdown` site

### ISSUE THREAD

**Issue by GegznaV** [tidyverse/broom#238]
Would you mind creating a [`pkgdown`](https://github.com/hadley/pkgdown) style website with online documentation for your package and publishing it as, e.g., [GitHub Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)?

**Comment by alexpghayes** [comment]
In progress. Closing in favor of #272.
