### ISSUE TITLE
Question and/or Feature Request

### ISSUE THREAD

**Issue by ptoche** [tidyverse/broom#243]
I like the package very much. It has a great future. My question and/or feature request starts from the following use-case: Extracting the intercept of ``lm``. 

    library(broom)
    td <- tidy(lm(mpg ~ wt, mtcars))

The following will do it:

      1. ``td[1, "estimate"]``
        ## [1] 37.28513

      2. ``td[td$term == "(Intercept)","estimate" ]``
        ## [1] 37.28513

The first approach has an obvious drawback: One must remember that the intercept is stored in the first row. 

The second approach has two issues: first, I must remember that the intercept has the strange name "(Intercept)" with brackets! and secondly the construct is somewhat roundabout.

Stop me right here if there is a third approach that is both intuitive and straightforward. If there is a better way, consider my post to be a **'Question'** rather than 'Feature Request'.

**Feature Request:** A version of ``broom``that would spit a  ``data.table``, say after setting an option like ``tidy(, data.table=TRUE)``. This would give tidier handles on the variables. With `` data.table`` I can write:

       3. ``ttd["intercept","estimate"]``

Currently, to get **3.**  I need a few steps:

        library("data.table")
        tdt <- as.data.table(td)
        tdt[1,"term"] <- "intercept"
        setkey(tdt)
        tdt["intercept","estimate"]
        ##    estimate
        ## 1: 37.28513

It would be most tidy to be able to get this after two steps:

    library(broom) # or library(broomDT)
    tdt <- tidy(lm(mpg ~ wt, mtcars), data.table=TRUE)
    tdt["intercept","estimate"]

**Comment by lemna** [comment]
@ptoche,

your first and third approach have the drawback that one can fit models without intercept, for example `td <- tidy(lm(mpg ~ -1 + wt, mtcars))`. The first row of `td` would be `wt` in this example.

Broom is part of the tidyverse, so it's probably most  attractive to stay within the tidyverse:
```R
library(tidyverse)
library(broom)
library(stringr)

td <- lm(mpg ~ wt, mtcars)
td %>%
  tidy() %>%
  filter(str_detect(term, "Intercept")) %>%
  select("estimate")
```
This has the advantage of catching two commonly used names for intercept terms, and it will return an empty data frame for models without intercept.

**Comment by alexpghayes** [comment]
And if you want the intercept as a vector you can use `pull` instead of `select`.

`data.table` is nice but the idioms don't match up with tidyverse idioms. The current plan is actually for `tidy`, `glance` and `augment` to return `tibble` objects. This should get implemented sometime this summer.
