### ISSUE TITLE
use texreg::extract for tidy

### ISSUE THREAD

**Issue by hughjonesd** [tidyverse/broom#249]
The `texreg` package extracts coefficients and goodness-of-fit statistics from 94 models, many of which aren't yet covered by broom. It would be easy to write a connector that outputs `tidy` results from `texreg::extract` results. Doing the same for `glance` would also be possible. Would you be open to this? If so, I can submit a pull request.

**Comment by dgrtwo** [comment]
This is a good idea! Now that I'm back to active maintenance of broom, would greatly appreciate a pull request.

**Comment by hughjonesd** [comment]
OK! It might also be worth talking to Philip Leifeld (@leifeld) about future directions. (And for that matter @leeper whose `prediction` package covers some similar areas...)

**Comment by alexpghayes** [comment]
Closing, details in #281.
