### ISSUE TITLE
Support for "emmGrid" class (replacing lsmobj). 

### ISSUE THREAD

**Issue by bengowan** [tidyverse/broom#253]
Hello, 

Just noting that the `lsmeans` package by @rvlenth is being deprecated for his new `emmeans` package. 
It replaces the lsmobj class with a new emmGrid class. 
If emmeans is loaded, lsmeans now also uses that class and `broom::tidy(lsmeans::lsmeans(fit, ~ x))` results in an error. 

I find the combination of tidy/lsmeans exceedingly useful and it would be great to see the compatibility continue to tidy/emmeans.  

Cheers,
Ben 

PS I'm very new to github, not sure how best I could contribute, but will see what I can do.

**Comment by rvlenth** [comment]
Looking at the code in `lsmeans_tidiers.R`, it appears this could be done by adding
```
#' @rdname lsmeans_tidiers
#' @export
tidy.emmGrid <- function(x, ...) {
    tidy_lsmeans(x, ...)
}
```
and adding these to the `repl` list in `tidy_lsmeans()`:
```
repl <- c(...
    emmeans = "estimate",
    pmmeans = "estimate",
    ...)
```
I suppose I could submit this as a pull request, but to date I'm still a bit uncomfortable myself with github operations.

Russ

**Comment by mjskay** [comment]
I've added a pull request for this: #252

**Comment by alexpghayes** [comment]
Closing this since the PR's been merged. Thanks all!
