### ISSUE TITLE
integer labels for `tidy.prcomp()` when missing from `prcomp` object

### ISSUE THREAD

**Issue by corybrunson** [tidyverse/broom#254]
Hi, i'm using **broom** with **tibble**, which discourages the use of row names, so that `tidy.prcomp` throws the error reproduced below. A simple fix was to assign the appropriate integer sequence to `labels`, which i've done at [this branch](/corybrunson/broom/tree/prcomp-labels). I didn't update documentation, but installing this change fixed my problem. I'm happy to send a PR but wanted to check first. (I couldn't find any discussion of this or reasons given not to.)

Thanks, both for any guidance and for the great package!

``` r
library(tibble)
library(broom)
test <- as.tibble(matrix(1:9, ncol = 3) + rnorm(n = 9, sd = 0.25))
test
#> # A tibble: 3 x 3
#>          V1       V2       V3
#>       <dbl>    <dbl>    <dbl>
#> 1 0.7009856 3.500583 6.987452
#> 2 2.1398779 5.031408 8.268146
#> 3 3.0907694 5.713359 8.464179
pca <- prcomp(test)
tidy(pca, matrix = "u")
#> Error in data.frame(label = rep(labels, times = ncomp), samples): arguments imply differing number of rows: 0, 9
rownames(test) <- 1:3
#> Warning: Setting row names on a tibble is deprecated.
pca <- prcomp(test)
tidy(pca, matrix = "u")
#>   row PC         value
#> 1   1  1 -2.006537e+00
#> 2   2  1  4.378777e-01
#> 3   3  1  1.568659e+00
#> 4   1  2  6.747315e-02
#> 5   2  2 -2.133301e-01
#> 6   3  2  1.458570e-01
#> 7   1  3  1.665335e-16
#> 8   2  3  2.220446e-16
#> 9   3  3  2.498002e-16
```

**Comment by grasshoppermouse** [comment]
I'm getting this bug too, although, weirdly, I am using a standard data frame that does have row names. For some reason, the rownames are getting dropped when prcomp converts my data frame to a matrix. 

In any case, the PR would solve my problem too.

**Comment by grasshoppermouse** [comment]
I didn't install your fork (and I don't know why I said it would fix my problem). The part of your patch that fixes my problem is reassigning the row names. Not sure why that works, though. I will investigate further.

**Comment by grasshoppermouse** [comment]
I think I figured it out. My data frame has "automatic" row names (1:n):

https://stat.ethz.ch/R-manual/R-devel/library/base/html/row.names.html

These are ignored when prcomp converts it to a matrix:

https://stat.ethz.ch/R-manual/R-devel/library/base/html/data.matrix.html

Thus, the resulting matrix does not have row names, thus $x does not have row names, and thus I hit this bug. 

Bottom line: I think anyone who uses prcomp with a data frame with "automatic" row names will hit this bug, and I think this PR will fix it.

**Comment by corybrunson** [comment]
Thanks for pointing that out! For the record: The second line of `stats::prcomp.default()` is `x <- as.matrix(x)` (see [`help(as.matrix)`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/matrix.html), so that, when `x` is a data frame, the default `rownames.force = NA` produces a matrix with or without row names depending on whether those of `x` are "automatic". This can't be controlled by the user. Again weirdly, whether the row names of a data frame are "automatic" is invisible even to `identical()`:

``` r
library(broom)
test <- as.data.frame(matrix(1:9, ncol = 3) + rnorm(n = 9, sd = 0.25))
test
#>          V1       V2       V3
#> 1 0.7707063 3.870905 7.091106
#> 2 2.3385348 4.987070 7.835155
#> 3 2.6638938 6.006691 8.690749
pca <- prcomp(test)
tidy(pca, matrix = "u")
#> Error in data.frame(label = rep(labels, times = ncomp), samples): arguments imply differing number of rows: 0, 9
test2 <- test
rownames(test2) <- 1:3
test2
#>          V1       V2       V3
#> 1 0.7707063 3.870905 7.091106
#> 2 2.3385348 4.987070 7.835155
#> 3 2.6638938 6.006691 8.690749
pca <- prcomp(test2)
tidy(pca, matrix = "u")
#>   row PC         value
#> 1   1  1 -1.760622e+00
#> 2   2  1  2.503534e-01
#> 3   3  1  1.510269e+00
#> 4   1  2  1.284867e-01
#> 5   2  2 -3.335669e-01
#> 6   3  2  2.050801e-01
#> 7   1  3 -1.110223e-16
#> 8   2  3  1.700029e-16
#> 9   3  3  1.110223e-16
identical(test, test2)
#> [1] TRUE
```

Anyway, you're right that my branch should fix this, and it does. I'll send the PR.
