### ISSUE TITLE
dealing with NULL

### ISSUE THREAD

**Issue by lemna** [tidyverse/broom#258]
Hi,

the readme states that "the output of the tidy, augment and glance functions is always a data frame" and "`glance` always returns a one-row data frame. The only exception is that `glance(NULL)` returns an empty data frame."

`tidy(NULL)` returns an empty data frame, but `augment(NULL)` and `glance(NULL)` return `NULL`. Is this a design decision?

**Comment by dgrtwo** [comment]
Whoops! It looks like that spec has been mistaken since the beginning, a bit embarrassing!

I did mean for each to return empty data frames. This has been fixed
