### ISSUE TITLE
Not compatible with SpeedGLM

### ISSUE THREAD

**Issue by vikram-rawat** [tidyverse/broom#259]
There is a packge for fast Linear regression called **speedglm**

This package is not working with broom. Not Everyday but most of the time I use this packge. Can you please look into it.

sample code
```

model<-speedlm(mpg~wt,data=mtcars)
broom::augment(model) %>% 
    plot_ly(x=~wt,showlegend=FALSE) %>% 
    add_markers(y=~mpg,color=I("darkblue"),size=I(30),alpha=.4) %>% 
    add_lines(y=~.fitted,color=I("red")) %>% 
    add_ribbons(ymin = ~ .fitted - 1.96 * .se.fit,
                ymax = ~.fitted+1.96 * .se.fit,color=I('grey')) %>% 
    config(displayModeBar=FALSE)

```

for big dataset it pays a lot Please at least look into it.

**Comment by dgrtwo** [comment]
Support for speedlm and speedglm models is added by #248
