### ISSUE TITLE
Add News.md to DESCRIPTION

### ISSUE THREAD

**Issue by helix123** [tidyverse/broom#263]
The `DESCRIPTION` file does not seem to contain an entries for a news file. This means, we do not see the news linked on the package's CRAN page

**Comment by alexpghayes** [comment]
I'm having some trouble figuring out how to add NEWS to the DESCRIPTION. [`dplyr`](https://cran.r-project.org/web/packages/dplyr/index.html) has a NEWS link on CRAN but I don't see any news entry in the DESCRIPTION file?

Happy to do this, just need to figure out how.

**Comment by alexpghayes** [comment]
I think removing `NEWS.md` from `.gitignore` in #264 was enough. Please reopen if the July release of `broom 0.5.0` doesn't link to `NEWS` on the CRAN page.
