### ISSUE TITLE
glance method for object of class DurbinWatsonTest

### ISSUE THREAD

**Issue by shabbybanks** [tidyverse/broom#266]
I think I can write this myself, but it would be helpful to have a `glance` method for an object of class `DurbinWatsonTest` from the `car` package. The return value has the following structure:
```
List of 4
 $ r          : num 0.0624
 $ dw         : num 1.85
 $ p          : num 0.304
 $ alternative: chr "two.sided"
 - attr(*, "class")= chr "durbinWatsonTest"
```

**Comment by alexpghayes** [comment]
If you're willing to write a PR, that'd be great. Otherwise let me know and I'll get to this at some point.

**Comment by shabbybanks** [comment]
This needn't be anything more than:
```
glance.durbinWatsonTest <- function(x) {
  data_frame(statistic=x$dw,p.value=x$p)
}
```

**Comment by mkuehn10** [comment]
Hi @alexpghayes I'd be interested in trying to do this.

**Comment by alexpghayes** [comment]
The approach to take here is the same as in my advice in #270. Again, reach out with any questions!

**Comment by mkuehn10** [comment]
I think the test failed because I didn't know how or where to add a dependency to the car package that durbinWatsonTest comes from.

**Comment by shabbybanks** [comment]
LGTM. Thanks for adding this.
