### ISSUE TITLE
tidy lavaan output

### ISSUE THREAD

**Issue by Ohlsen** [tidyverse/broom#27]
Hi! 
It would be cool to have tidy output for the lavaan-package (https://github.com/yrosseel/lavaan) which is used for structural equation modeling and cfa.
Thanks =)

**Comment by dgrtwo** [comment]
I'd also like to have that included! But I've put some time into exploring tidying methods for lavaan objects, and the objects are pretty intense. Take a look, for instance, at `getMethod(summary, "lavaan")`: there are many possible contents depending on the kind of fit, and some of them are stored in a counterintuitive way.

It's also unclear what the tidy results would be, as each latent variable model stores multiple tables. I'm sure it's possible to construct a tidied version, but I'm worried I might not be the one to do it (as I'm not familiar with the package as a user).

If you had some specific ideas for the input and output for tidying methods (or better yet, code for some of them) I'd be very happy to help incorporate them into the package!

One thing I was able to cook up was a glance method, but that's just a start:

    glance.lavaan <- function(x, ...) {
      ret <- as.data.frame(t(unclass(fitMeasures(x))))
      # rename some to fit conventions of the package
      ret <- plyr::rename(ret, c(aic = "AIC", bic = "BIC", logl = "logLik"))
      names(ret) <- gsub("pvalue", "p.value", names(ret))
      ret
    }

**Comment by tjmahr** [comment]
Just chiming in to agree that `glance` would wrap `fitmeasures`, and note that `tidy` would wrap `parameterestimates`.

**Comment by puterleat** [comment]
Ive added a PR which includes glance and tidy methods. Needs some thought to work out what augment should do.

**Comment by DominiqueMakowski** [comment]
Any advances on this?

**Comment by alexpghayes** [comment]
You can follow along at #233. Adding new tidiers is not the highest priority at the moment, so if you're hoping for new tidiers sooner rather than later the best way is to make a PR.

**Comment by alexpghayes** [comment]
Merged! Small changes likely to come to the column names in `glance` before the `broom 0.5.0` release.
