### ISSUE TITLE
tidy and augment Methods for caret::confusionMatrix

### ISSUE THREAD

**Issue by benwhalley** [tidyverse/broom#270]
How about something like this:

```
cm <- caret::confusionMatrix(rbinom(100,3,.5),rbinom(100,3,.5))

tidy.cm <- function(cm){
  cml <- cm$overall %>% as.list()
  data_frame(statistic = c("Accuracy", "Kappa"), 
             estimate = c(cml$Accuracy, cml$Kappa),
             lower = c(cml$AccuracyLower, NA),
             upper = c(cml$AccuracyUpper, NA),
             p.value = c(cml$AccuracyPValue, cml$McnemarPValue))
}

augment.cm <- function(cm){
  cm$byClass %>% as.data.frame()
}


tidy.cm(cm)
augment.cm(cm)
```

Do people have feelings about the col names for augment?

**Comment by amcadie** [comment]
@benwhalley I was going to open this very issue, but you beat me to it!

One tweak could be to add a %>% t( ) to the augment.cm function so that it is easy to rbind output from several models.

Thanks for suggesting this!

**Comment by randomgambit** [comment]
hello there and thanks for this life-saving package!! is `broom` able to work with `caret` natively? thanks!

**Comment by alexpghayes** [comment]
Sounds good. You'll want to start by forking the broom repository, and then cloning it to your computer. Once you have it on your local computer, you can start create a new file (probably call it `R/caret_tidiers.R`). Then you'll want to add the functions defined above, except make sure they return tibbles.

After you've get the functions working the way you want, you'll want to [document their behavior](http://r-pkgs.had.co.nz/man.html).

Then next step will be to [write some tests](http://r-pkgs.had.co.nz/tests.html) to ensure that your functions are working correctly. You'll want to create a file `tests/testthat/test-caret.R` and then write the tests there.

Once the tests are passing, the final step is to commit all your work to your fork, and then open a pull request to `broom`.

A good general reference is Hadley Wickham's book R Packages, which I've linked to above.  You should also take a look the [vignette on new tidiers](http://broom.tidyverse.org/articles/adding-tidiers.html).

It's easy to get information overload, so just drop me a question anytime!

**Comment by mkuehn10** [comment]
Does only a tidy function (and possibly a glance function) make sense for a confusionMatrix?  

The tidy data frame would have the Accuracy, Kappa, Sensitivity, Pos Pred Value, Neg Pred Value, Precision, Recall, F1, Prevalence, Detection Rate, Detection Prevalence, and Balanced Accuracy for each row with lower and upper limits on the Accuracy and p values for the Accuracy and Kappa.  I would need to examine the best way to set this up for the case when there are more than 2 classes.

I don't think the description of the augment function [here](http://broom.tidyverse.org/articles/adding-tidiers.html) would be the output of the $byClass portion of the confusionMatrix (as shown in the original comment by @benwhalley ).  I think all of this should be included in tidy.

As far as a glance function, maybe this would be just be the Accuracy and Kappa values for when there are more than 2 classes and it could have all of the other metrics listed above but without the confidence interval for the Accuracy and the p values for the Accuracy and Kappa.

**Comment by mkuehn10** [comment]
Here is what the output would look like with only 2 classes:

`cm2 <- caret::confusionMatrix(factor(binom(100,1,.5)),factor(rbinom(100,1,.5)))`
`tidy(cm2)`

|term                 |  estimate|     lower|     upper|   p.value|
|:--------------------|---------:|---------:|---------:|---------:|
|Accuracy             | 0.5100000| 0.4080363| 0.6113558| 0.9049645|
|Kappa                | 0.0144811|        NA|        NA| 0.5677092|
|Sensitivity          | 0.5263158|        NA|        NA|        NA|
|Specificity          | 0.4883721|        NA|        NA|        NA|
|Pos Pred Value       | 0.5769231|        NA|        NA|        NA|
|Neg Pred Value       | 0.4375000|        NA|        NA|        NA|
|Precision            | 0.5769231|        NA|        NA|        NA|
|Recall               | 0.5263158|        NA|        NA|        NA|
|F1                   | 0.5504587|        NA|        NA|        NA|
|Prevalence           | 0.5700000|        NA|        NA|        NA|
|Detection Rate       | 0.3000000|        NA|        NA|        NA|
|Detection Prevalence | 0.5200000|        NA|        NA|        NA|
|Balanced Accuracy    | 0.5073439|        NA|        NA|        NA|

Given the confusionMatrix in the original issue, this is what the tidy would output:

`cm <- caret::confusionMatrix(factor(binom(100,3,.5)),factor(rbinom(100,3,.5)))`
`tidy(cm)`

|term                          |  estimate|     lower|     upper|   p.value|
|:-----------------------------|---------:|---------:|---------:|---------:|
|Accuracy                      | 0.3200000| 0.2302199| 0.4207669| 0.9394611|
|Kappa                         | 0.0067193|        NA|        NA| 0.9685678|
|Sensitivity Class: 0          | 0.1818182|        NA|        NA|        NA|
|Sensitivity Class: 1          | 0.3846154|        NA|        NA|        NA|
|Sensitivity Class: 2          | 0.3684211|        NA|        NA|        NA|
|Sensitivity Class: 3          | 0.0833333|        NA|        NA|        NA|
|Specificity Class: 0          | 0.8876404|        NA|        NA|        NA|
|Specificity Class: 1          | 0.5573770|        NA|        NA|        NA|
|Specificity Class: 2          | 0.7096774|        NA|        NA|        NA|
|Specificity Class: 3          | 0.8522727|        NA|        NA|        NA|
|Pos Pred Value Class: 0       | 0.1666667|        NA|        NA|        NA|
|Pos Pred Value Class: 1       | 0.3571429|        NA|        NA|        NA|
|Pos Pred Value Class: 2       | 0.4375000|        NA|        NA|        NA|
|Pos Pred Value Class: 3       | 0.0714286|        NA|        NA|        NA|
|Neg Pred Value Class: 0       | 0.8977273|        NA|        NA|        NA|
|Neg Pred Value Class: 1       | 0.5862069|        NA|        NA|        NA|
|Neg Pred Value Class: 2       | 0.6470588|        NA|        NA|        NA|
|Neg Pred Value Class: 3       | 0.8720930|        NA|        NA|        NA|
|Precision Class: 0            | 0.1666667|        NA|        NA|        NA|
|Precision Class: 1            | 0.3571429|        NA|        NA|        NA|
|Precision Class: 2            | 0.4375000|        NA|        NA|        NA|
|Precision Class: 3            | 0.0714286|        NA|        NA|        NA|
|Recall Class: 0               | 0.1818182|        NA|        NA|        NA|
|Recall Class: 1               | 0.3846154|        NA|        NA|        NA|
|Recall Class: 2               | 0.3684211|        NA|        NA|        NA|
|Recall Class: 3               | 0.0833333|        NA|        NA|        NA|
|F1 Class: 0                   | 0.1739130|        NA|        NA|        NA|
|F1 Class: 1                   | 0.3703704|        NA|        NA|        NA|
|F1 Class: 2                   | 0.4000000|        NA|        NA|        NA|
|F1 Class: 3                   | 0.0769231|        NA|        NA|        NA|
|Prevalence Class: 0           | 0.1100000|        NA|        NA|        NA|
|Prevalence Class: 1           | 0.3900000|        NA|        NA|        NA|
|Prevalence Class: 2           | 0.3800000|        NA|        NA|        NA|
|Prevalence Class: 3           | 0.1200000|        NA|        NA|        NA|
|Detection Rate Class: 0       | 0.0200000|        NA|        NA|        NA|
|Detection Rate Class: 1       | 0.1500000|        NA|        NA|        NA|
|Detection Rate Class: 2       | 0.1400000|        NA|        NA|        NA|
|Detection Rate Class: 3       | 0.0100000|        NA|        NA|        NA|
|Detection Prevalence Class: 0 | 0.1200000|        NA|        NA|        NA|
|Detection Prevalence Class: 1 | 0.4200000|        NA|        NA|        NA|
|Detection Prevalence Class: 2 | 0.3200000|        NA|        NA|        NA|
|Detection Prevalence Class: 3 | 0.1400000|        NA|        NA|        NA|
|Balanced Accuracy Class: 0    | 0.5347293|        NA|        NA|        NA|
|Balanced Accuracy Class: 1    | 0.4709962|        NA|        NA|        NA|
|Balanced Accuracy Class: 2    | 0.5390492|        NA|        NA|        NA|
|Balanced Accuracy Class: 3    | 0.4678030|        NA|        NA|        NA|

**Comment by mkuehn10** [comment]
If `by_class = FALSE`, then that would remove all of those terms from the output since there isn't an overall Sensitivity, etc.  For the 2 class case, it only lists one because the other can be inferred by 1 - Sensitivity.

Thanks for the feedback.  I'll work on it some more tomorrow!

**Comment by alexpghayes** [comment]
Right, then it should just have an `Accuracy` and `Kappa` column like in the `glance` above.

Sounds good. No rush.
