### ISSUE TITLE
Glance Feature Request

### ISSUE THREAD

**Issue by jbryer** [tidyverse/broom#274]
It would be nice to have a parameter/argument to the `glance` function to specify which statistics (i.e. columns) to return. The default is typically too wide for PDF output.

**Comment by alexpghayes** [comment]
What about using `dplyr::select` since the output from `glance` is a dataframe?

```r
library(broom)
library(dplyr)

lm(mpg ~ ., mtcars) %>% 
  glance() %>% 
  select(logLik, AIC, BIC)
#>      logLik      AIC      BIC
#> 1 -69.85491 163.7098 181.2986
```

**Comment by dgrtwo** [comment]
I agree; this would be a lot of implementation (done in every `glance()` function, or done as a layer in front of them) that could be replaced by using `select()`
