### ISSUE TITLE
allow exponentiate argument when tidying a glmer model

### ISSUE THREAD

**Issue by larmarange** [tidyverse/broom#276]
When tidying the result of a glmer model, the `exponentiate` argument doesn't work.

**Comment by alexpghayes** [comment]
It's not currently implemented, but I can see how that could be useful.

**Comment by larmarange** [comment]
do you need a PR?

**Comment by alexpghayes** [comment]
That'd be wonderful!

**Comment by larmarange** [comment]
Should that feature be applied directly in `broom.mixed` as it is `tidy.merMod` method that should be updated?

**Comment by alexpghayes** [comment]
Yes! Closing this in favor of the `broom.mixed` issue.
