### ISSUE TITLE
df in glance for lm

### ISSUE THREAD

**Issue by hardin47** [tidyverse/broom#278]
I'm wondering why the `df` in `glance` applied to `lm` are `p` instead of `p-1`?  That is, the `glance` output seems to indicate that the `df` are associated with the corresponding F-test, but the numerator `df` are not correct.

```
summary(lm(hwy ~ cty, data = ggplot2::mpg))
glance(lm(hwy ~ cty, data = ggplot2::mpg))
```

**Comment by gavinsimpson** [comment]
See #273 for a discussion.

**Comment by dgrtwo** [comment]
As described in the other issue, I've come around on this!
