### ISSUE TITLE
output of tidy.kde is not tidy data

### ISSUE THREAD

**Issue by hughjonesd** [tidyverse/broom#284]
From https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html, one non-tidy form of data is "Column headers are values, not variable names". The output of tidy.kde looks like this:

```
         x1        x2        x3 estimate
1 -3.516990 -4.284105 -2.930475        0
2 -3.381653 -4.284105 -2.930475        0
3 -3.246316 -4.284105 -2.930475        0
4 -3.110980 -4.284105 -2.930475        0
5 -2.975643 -4.284105 -2.930475        0
6 -2.840307 -4.284105 -2.930475        0
...
```

and the numbers of dimensions vary. I think the solution is
```
tidyr::gather(x, dimension, value, - estimate)
```

**Comment by alexpghayes** [comment]
In this case `x1`, `x2` and `x3` are names of dimensions of data. Since each row corresponds to an observation I think this qualifies as tidy.

I'm going to close this for now but would be happy to consider examples where `gather`ing is helpful.
