### ISSUE TITLE
Kendall

### ISSUE THREAD

**Issue by jjvenky** [tidyverse/broom#285]
The Mann-Kendall trend test is often used for time series analysis instead of a straight `lm(y~time)`. The [Kendall](https://CRAN.R-project.org/package=Kendall) package implements a few ways of doing this test.

The `Kendall::MannKendall` and `Kendall::SeasonalMannKendall` functions work with time series, `ts()`, data. The simple `Kendall::Kendall` works with two vectors of equal length.

The basic example from the help file is:

```r
A<-c(2.5,2.5,2.5,2.5,5,6.5,6.5,10,10,10,10,10,14,14,14,16,17)
B<-c(1,1,1,1,2,1,1,2,1,1,1,1,1,1,2,2,2)
Kendall(A,B)
```

yielding the output:

```
tau = 0.318, 2-sided pvalue =0.19108
```

The `summary()` gives a little more information:

```
summary(Kendall(A,B))
Score =  22 , Var(Score) = 258
denominator =  69.28203
tau = 0.318, 2-sided pvalue =0.19108
```

The output of `Kendall::Kendall` is a List of length 5. It would be very useful enhancement to have `broom` handle the outputs of this type of model. Thanks.

**Comment by cimentadaj** [comment]
@alexpghayes If you're alright, I'd love to take stab at it and send a PR.

**Comment by cimentadaj** [comment]
@alexpghayes I've issued pull request https://github.com/tidyverse/broom/pull/343 with all the information request in the `broom` website implementing this.

**Comment by jjvenky** [comment]
Thank you @cimentadaj & @alexpghayes
