### ISSUE TITLE
tidy not producing proper output for multinom 

### ISSUE THREAD

**Issue by abnormally-distributed** [tidyverse/broom#286]
I am having an issue where the tidy function is not at all correct for a model fit with multinom. Below is an example. The output pasted here is a little ugly, but focus on what I put in boldface. Note that the proper coefficient is ~63 for B's Intercept. Tidy is instead returning 3.363218e+27. 

The data used is attached

[Wine_Data.zip](https://github.com/tidyverse/broom/files/1778298/Wine_Data.zip)

The code used below

```
`library(nnet)
multi = multinom(Cultivar ~   Alcohol + log(Malic.acid) + Phenols , data=wine)

tidy(multi, conf.int=TRUE)`

```

Proper output from summary(multi)

> Coefficients:
  (Intercept)    Alcohol log(Malic.acid)   Phenols
B    **63.38270** -4.3939661       -1.560030 -1.960664
C    18.96088 -0.6131522        1.465838 -5.385272

Std. Errors:
  (Intercept)   Alcohol log(Malic.acid)   Phenols
B    10.78404 0.7908928       0.8526257 0.8738783
C    10.63976 0.7808892       0.8744278 0.9896227

What tidy(multi) is giving me instead:

> y.level term estimate std.error statistic p.value
B1	   B	(Intercept)	**3.363218e+27**	10.7840410	5.8774531	4.166266e-09	
B2	   B	Alcohol	1.235164e-02	0.7908928	-5.5557038	2.764953e-08	
B3	   B	log(Malic.acid)	2.101297e-01	0.8526257	-1.8296778	6.729813e-02	
B4	   B	Phenols	1.407649e-01	0.8738783	-2.2436355	2.485586e-02	
C1	   C	(Intercept)	1.716342e+08	10.6397575	1.7820778	7.473654e-02	
C2	   C	Alcohol	5.416408e-01	0.7808892	-0.7851974	4.323378e-01	
C3	   C	log(Malic.acid)	4.331171e+00	0.8744278	1.6763396	9.367170e-02	
C4	  C	Phenols	4.583595e-03	0.9896227	-5.4417423	5.276196e-08

**Comment by alexpghayes** [comment]
No problem! Glad you figured it out. Gonna close this issue.
