### ISSUE TITLE
broom for tseries::garch models 

### ISSUE THREAD

**Issue by lrnv** [tidyverse/broom#288]
Hi, 

I'm trying to work with a lot of garch models from the tseries packages. 

Since there is no broom's function for thoose models, i'm trying to write my own. 

exploring the moels via : 
```
str(my_garch)
str(summary(my_garch))
?garch
```

I concluded with the following functions : 
```
garch.glance <- function(garch){
  p <- list()
  p$logLik = - (garch$n.likeli)
  p$j.b.p.value = summary(garch)$j.b.test$p.value
  p$l.b.p.value = summary(garch)$l.b.test$p.value
  return(as.data.frame(p))
}
garch.tidy <- function(garch){
return(as.data.frame(summary(garch)$coef))
}
```

But i still dont get how to make my function to be called by "tidy" when it encounters a "garch" object...

besides that, if you have modifications to apport to my functions (especialy in the tests part ?), be free to do so. 

Besides that again, if you wanna turn this into a pull request (dunno how to do so), you can :)

**Comment by wilsonfreitas** [comment]
I've submitted a PR with the tidy method implemented.

**Comment by alexpghayes** [comment]
Thanks y'all. I'm gonna close this issue and suggest moving additional discussion to #295.
