### ISSUE TITLE
broom::tidy on SpatialPolygonsDataFrame -- memory issues?

### ISSUE THREAD

**Issue by kfeilich** [tidyverse/broom#290]
I've been trying to use broom::tidy() on a SpatialPolygonsDataFrame to facilitate plotting in ggplot2. When I load the original data as a SpatialPolygons dataframe, the data are ~347 Mb, with 2121 objects. After executing broom.tidy() on that object, the resulting output is over 11Gb, and crashes R and my computer. 

I have 16GB memory, running R v. 3.4.3  (broom v. 0.4.3) on Ubuntu 16.04 (Dell XPS 13). Can someone explain why the output of broom.tidy is so much larger than the input? Alternatively, is there a way to plot spatial objects in ggplot without using broom::tidy, or finding some other way to keep the memory low? 

Here's the particular code. The dataset is a subset of the USGS watershed boundary dataset.
`wbd <- readOGR(dsn = "data/huc", layer="WBDHU8_lower48")  # Import clipped WBD`
`wbd@data <- left_join(wbd@data, family.hu.avgs, by = c("HUC8"="HUC8"))` 
NB: family.hu.avgs is a very small DataFrame
`wbd_tidy <- broom::tidy(wbd)  # Convert to dataframe for ggplot`  <- first crash
`wbd$id <- row.names(wbd)  # Set ID for left_join`
`wbd_tidy <- left_join(wbd_f, wbd@data)`

Thanks.

**Comment by alexpghayes** [comment]
Don't know enough about spatial tidiers at the moment to comment on the memory usage, but the development version of [`ggplot2`](https://github.com/tidyverse/ggplot2) now supports `sf` and hopefully makes this intermediate step unnecessary.

**Comment by mdsumner** [comment]
You might try `spbabel::sptable` rather than fortify or tidy, should be a lot faster. 

It uses different column names but this is enough to get what fortify returns: 

```R
rename(id = object_, group = branch_, x = x_, y = y_)
```

(I always meant to contribute sptable logic to broom, but sf stole the show. I've also learnt a lot since writing spbabel and have moved on somewhat but not with anything on CRAN yet). 

For a purely sf approach use `st_coordinates` that returns a matrix, with extra columns L1, L2, L3 as needed - multipolygon needs all three.

**Comment by mdsumner** [comment]
Also, @kfeilich I'd recommend only joining on the columns you really need - it looks like you copy on more columns than you'd use in a plot? (Just checking)

**Comment by kfeilich** [comment]
Thanks @mdsumner ! I ended up switching over to a fully sf approach, and it ended up running a LOT faster. I had been only joining the data columns I needed, but still was fairly slow. Thankfully everything  is working at a reasonable pace now.

**Comment by rafarafarafa** [comment]
Hi @kfeilich, I know it has been a little while, but could you show how this was solved?
