### ISSUE TITLE
Tieders for ordinal models

### ISSUE THREAD

**Issue by larmarange** [tidyverse/broom#292]
I have developed a generic tidier for model outputs that could be applied to a different range of models. Although it is not covering all specificity of a specific model, it's an easy way to cover more models.

That generic tidier provides estimates, p-values and confidence intervals of estimates.

The code is available here: https://github.com/larmarange/JLutils/blob/master/R/tidy_model.R if of interest.

**Comment by alexpghayes** [comment]
These seem potentially useful, but I'm having a hard time figuring out which objects they work on. Where do `clm`, `clmm` and `svyolr` objects come from? I'd be happy to add tidiers for these specific models to broom with a little bit more information.

**Comment by larmarange** [comment]
That generic tieder is working when  `coef` and `summary` methods have been properly developed for a specif model and constitant with generic methods.

`clm` and `clmm` models are provided by the `ordinal` package. `svyolr` comes from `survey` package.

**Comment by larmarange** [comment]
I will prepare a PR for clm, clmm and svyolr tidiers. Do you prefer 2 distinct PR (one for ordinal objects and one for survey objects)?

No problem for the generic tieder. It is useful for advanced users who are ready to test things, but not for basic usage.

**Comment by alexpghayes** [comment]
Great. A single PR is fine.

**Comment by alexpghayes** [comment]
Closing as #332 has been merged. Thanks!
