### ISSUE TITLE
FR: support glmnetUtils variants of glmnets

### ISSUE THREAD

**Issue by stephlocke** [tidyverse/broom#300]
glmnetUtils allows us to use formula syntax and supply data.frames to glmnet by transforming them first. Unfortunately, this seems to break the `*.glmnet` methods. It'd be great if these could be supported.

```
broom::tidy(glmnetUtils::glmnet(Species ~., data=iris ,
            family = "multinomial"))
```

Current error:
> Error in is.data.frame(data) : 
 > argument "data" is missing, with no default

**Comment by alexpghayes** [comment]
I think this is a good idea, but the tidiers probably would fit best in `glmnetUtils`. Ideally someone could make a PR to `glmnetUtils` based off the current `glmnet` tidiers, or perhaps @Hong-Revo would be willing to implement those.

I'm going to let this sit for now and will come back to it later in the summer if tidiers don't get added to `glmnetUtils`.

**Comment by abnormally-distributed** [comment]
I've found the best solution is to just use the model matrix. This way you
can use a formula interface to easily specify the model however you want.

For example (using . to represent all variables, but you can specify y ~ x1
+ x2, etc):

x = model.matrix( y ~ . , data=data)[,-1]
y = data$y

then just use with glmnet as glmnet(x, y)

**Comment by Hong-Revo** [comment]
I didn't see this FR until today. I'll see if I can do something.

**Comment by Hong-Revo** [comment]
Having a look at what `broom::tidy` does now. Could someone explain to me the output when applied to a glmnet object? Also, is the warning intended?

```r
m <- glmnet::glmnet(x=model.matrix(~., iris[1:4]), y=iris$Species,
                    family="multinomial", nlambda=20)
broom::tidy(m)

#         class         term step      estimate lambda dev.ratio
#1       setosa                NA  6.414140e-16     NA        NA
#2   versicolor                NA -1.622400e-15     NA        NA
#3    virginica                NA  9.809861e-16     NA        NA
#4       setosa                NA  1.044822e+00     NA        NA
...
#164  virginica Sepal.Length   NA -1.647827e-02     NA        NA
#165  virginica  Sepal.Width   NA -6.276845e+00     NA        NA
#166  virginica Petal.Length   NA  8.922528e+00     NA        NA
#167  virginica  Petal.Width   NA  1.723847e+01     NA        NA

#Warning message:
#In evalq(as.numeric(step), <environment>) : NAs introduced by coercion

```

**Comment by alexpghayes** [comment]
This looks like a bug for the multinomial family.

In general the behavior is more like:

```r
x <- model.matrix(~ . - 1, iris[1:3])
y <- iris[, 4]
m <- glmnet::glmnet(x, y)
broom::tidy(m)
#> Warning: package 'bindrcpp' was built under R version 3.4.4
#>             term step     estimate       lambda dev.ratio
#> 1    (Intercept)    1  1.199333333 0.7314817699 0.0000000
#> 2    (Intercept)    2  1.060533237 0.6664989456 0.1574070
#> 3   Petal.Length    2  0.036934565 0.6664989456 0.1574070
#> 4    (Intercept)    3  0.934063759 0.6072890162 0.2880890
#> 5   Petal.Length    3  0.070587966 0.6072890162 0.2880890
#> 6    (Intercept)    4  0.818829480 0.5533391338 0.3965835
#> 7   Petal.Length    4  0.101251691 0.5533391338 0.3965835
#> 8    (Intercept)    5  0.713832297 0.5041820103 0.4866576
#> 9   Petal.Length    5  0.129191335 0.5041820103 0.4866576
#> 10   (Intercept)    6  0.618162775 0.4593918701 0.5614386
...
```

**Comment by alexpghayes** [comment]
The idea is to have a data frame where the `term` column contains the feature name, the `step` column indexes `lambda`, `estimate` is the coefficient estimate for that `lambda`, and `dev.ratio` is the fraction of the null deviance explained at a particular value of `lambda`.

**Comment by Hong-Revo** [comment]
The root cause of the error is that `tidy.glmnet` calls the `coef.glmnet` directly, instead of using S3 method dispatch. glmnetUtils defines its own `coef` (and `predict`) method for objects that it creates. If you just call `coef`, then everything should work (modulo the separate issue of the multinomial family not being supported).
