### ISSUE TITLE
Give Alex Hayes write access to broom repo

### ISSUE THREAD

**Issue by dgrtwo** [tidyverse/broom#310]
On Monday @alexpghayes will be starting as an intern on the broom package. Ever since this moved to tidyverse org I'm not an owner: could someone please grant him write access?

cc @hadley @batpigandme

**Comment by batpigandme** [comment]
Done! 🎉

**Comment by hadley** [comment]
Let me know if you want any advice on how to triage the issues.

**Comment by alexpghayes** [comment]
Thanks. Early next week I'm chatting with Dave and after that I'll have a better idea of the overall direction of the project. Will run the initial plan by you after that.

**Comment by alexpghayes** [comment]
@hadley Can I get access to the AppVeyor project? Can't see why the build is failing.

**Comment by hadley** [comment]
That is a surprisingly question. Can you ask on slack? It's likely to need a bit of exploration.
