### ISSUE TITLE
See if there's a way to speed up the nlme tests

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/broom#311]

**Comment by alexpghayes** [comment]
Closing since `nlme` tidiers will be moved to [broom.mixed](https://github.com/bbolker/broom.mixed) and deprecated.

**Comment by wilsonfreitas** [comment]
Ok, but in the meantime, how to skip the nlme tests? This is lasting forever in my environment.

**Comment by alexpghayes** [comment]
In the test body, add `skip("Some informative message")`.

For example:

```r
test_that("skip example", {
  expect_equal(1, 1L)    # this expectation runs
  skip('skip')
  expect_equal(1, 2)     # this one skipped
  expect_equal(1, 3)     # this one is also skipped
})
```
