### ISSUE TITLE
Don't fall back to as.data.frame

### ISSUE THREAD

**Issue by dgrtwo** [tidyverse/broom#350]
When I first started broom I thought as.data.frame would be a reasonable fallback, but this was a mistake (it makes the error message more confusing and the behavior less controlled).

I think it should give a helpful message ("we don't have a tidier for model X, but you can go to <github> to open a feature request or pull request.")

This is a breaking change so let's get it in with 0.5.0 release

**Comment by alexpghayes** [comment]
In 2f61cb4059d36a647207b274d7bd96b8c
