### ISSUE TITLE
broom::tidy throws error on quantreg::rq model when run on a constant

### ISSUE THREAD

**Issue by lboller** [tidyverse/broom#354]
The broom tidier `tidy.rq` fails on a quantile regression run on a constant. It appears that the underlying tidying method expects a confidence interval in the `coefficients` object of the `summary` object.

The tidier works as expected on a simple bivariate quantile regression. See the reprex below.

``` r
quantreg::rq(mpg ~ 1, data = mtcars)
#> Warning in rq.fit.br(x, y, tau = tau, ...): Solution may be nonunique
#> Call:
#> quantreg::rq(formula = mpg ~ 1, data = mtcars)
#> 
#> Coefficients:
#> (Intercept) 
#>        19.2 
#> 
#> Degrees of freedom: 32 total; 31 residual
broom::tidy(quantreg::rq(mpg ~ 1, data = mtcars))
#> Warning in rq.fit.br(x, y, tau = tau, ...): Solution may be nonunique
#> Error in names(object) <- nm: 'names' attribute [3] must be the same length as the vector [1]
quantreg::rq(mpg ~ cyl, data = mtcars)
#> Call:
#> quantreg::rq(formula = mpg ~ cyl, data = mtcars)
#> 
#> Coefficients:
#> (Intercept)         cyl 
#>        36.8        -2.7 
#> 
#> Degrees of freedom: 32 total; 30 residual
broom::tidy(quantreg::rq(mpg ~ cyl, data = mtcars))
#>          term estimate  conf.low conf.high tau
#> 1 (Intercept)     36.8 30.034290 42.402710 0.5
#> 2         cyl     -2.7 -3.465376 -1.792312 0.5
```

**Comment by erleholgersen** [comment]
I'd like to take a stab at this! Digging a bit further into the underlying quantreg functions, it appears that confidence intervals are not calculated when there is only a single term in the model. You run into the same problem if you fit a model without intercept:

``` r
broom::tidy(quantreg::rq(mpg ~ cyl - 1, data = mtcars))
#> Error in names(object) <- nm: 'names' attribute [3] must be the same length as the vector [1]
```

In terms of fixing this bug, do we want to return a data frame with only the columns `term`, `estimate`, and `tau`? Or would it be better to keep the return object dimensions constant and set `conf.low` and `conf.high` to NA?
