### ISSUE TITLE
`broom::tidy()` does not work with `lmerTest`

### ISSUE THREAD

**Issue by strengejacke** [tidyverse/broom#361]
models fitted with `lmerTest` cause error when used with `broom::tidy()`

```r
library(lme4)
fm1 <- lmerTest::lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
broom::tidy(fm1)
#> Error in vector(type, length) : 
#>   vector: cannot make a vector of mode 'NULL'.

broom::tidy(fm1, effects = "fixed")
#>          term  estimate std.error statistic   p.value           NA
#> 1 (Intercept) 251.40510  6.824556  17.00001 36.838311 1.170875e-17
#> 2        Days  10.46729  1.545789  17.00000  6.771485 3.263790e-06
```

using `lme4::lmer()` works fine.

**Comment by nutterb** [comment]
Is this the same as #309?

**Comment by strengejacke** [comment]
Yes, looks like that.

**Comment by BoiChaza** [comment]
hi i have previously used sjt.lmer() to produce linear mixed summaries as html table, however using the same code i now get the below error message. 
Error: Column 6 must be named

does anyone have an idea of how to solve this please? thanks in advance

**Comment by strengejacke** [comment]
Re-fit the model with `lme4::lmer()` and don't load the _lmerTest_ library.

**Comment by strengejacke** [comment]
Yes, I'll keep track of the broom.mixed development. Maybe I'll add a temporary solution (i.e. own tidier) for lmerTestMerMod-objects meanwhile...

**Comment by BoiChaza** [comment]
thanks Strengejacke it worked, albeit an extremely slow computation. i did not use p.kr =FALSE though

Boi

**Comment by alexpghayes** [comment]
@strengejacke Is there a way you could re-export the `broom.mixed` tidiers so you don't have to rewrite them?

**Comment by strengejacke** [comment]
@alexpghayes Sorry, I think I don't know what you exactly mean. Which tidiers from which would you recommend to re-export?
