### ISSUE TITLE
Deprecate `glance.matrix` and `tidy.matrix`?

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/broom#364]
There are better tools for type conversion in `tibble` that would be preferable.

**Comment by alexpghayes** [comment]
Similar the tidiers for vectors should be deprecated in favor of `tibble::enframe`

**Comment by jsta** [comment]
For people finding this in search engine results:
> the Matrix and vector tidiers have been deprecated in favor of `tibble::as_tibble()` and `tibble::enframe()`
