### ISSUE TITLE
including p-values in tidy output for `lmer` models

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/broom#372]
This line in the code suggests that sometimes it's possible to output p-values for `lmer` models. How can I do this?

https://github.com/tidyverse/broom/blob/c9467bfdee14dfacd91e3a6f554b60f622e6f756/R/lme4_tidiers.R#L99

Currently, I don't get any p-values:
``` r
library(lme4)
#> Loading required package: Matrix
library(broom)

broom::tidy(lme4::lmer(
  formula = Reaction ~ Days + (Days | Subject),
  data = lme4::sleepstudy
))
#>                           term     estimate std.error statistic    group
#> 1                  (Intercept) 251.40510485  6.824556 36.838311    fixed
#> 2                         Days  10.46728596  1.545789  6.771485    fixed
#> 3       sd_(Intercept).Subject  24.74044759        NA        NA  Subject
#> 4              sd_Days.Subject   5.92213327        NA        NA  Subject
#> 5 cor_(Intercept).Days.Subject   0.06555133        NA        NA  Subject
#> 6      sd_Observation.Residual  25.59181589        NA        NA Residual
```

However, if I include `glmer` model, then I do get the p-values by default:
``` r

broom::tidy(lme4::glmer(
  formula = cbind(incidence, size - incidence) ~ period + (1 | herd),
  data = lme4::cbpp,
  family = binomial
))
#>                  term   estimate std.error statistic      p.value group
#> 1         (Intercept) -1.3983429 0.2312140 -6.047828 1.468113e-09 fixed
#> 2             period2 -0.9919250 0.3031506 -3.272053 1.067695e-03 fixed
#> 3             period3 -1.1282162 0.3228301 -3.494767 4.744754e-04 fixed
#> 4             period4 -1.5797454 0.4220492 -3.743037 1.818098e-04 fixed
#> 5 sd_(Intercept).herd  0.6420699        NA        NA           NA  herd
```

I am writing a wrapper around these functions and so I need a consistent output across these two functions. If `p.value` is missing form `lmer` models entered into `tidy`, the functions fail. So I want to make sure that there are always p-values for `lmer` tidy outputs.

Thanks.

Created on 2018-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by alexpghayes** [comment]
I'm not particular familiar with these tidiers so I can't help you off the bat unfortunately. These tidiers are actually about to be deprecated in broom (#329), and so you're probably better of asking in [`broom.mixed`](https://github.com/bbolker/broom.mixed). I agree that consistency would be good in this case, or if that isn't possible, maybe some more obvious documentation. bbolker/broom.mixed#2

**Comment by nutterb** [comment]
The short answer is that you won't get p-values from a `lmer`.  Some links to explain why are

* https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html
* https://daijiang.name/en/2015/06/22/why-no-p-values-in-mixed-models/
* https://stat.ethz.ch/pipermail/r-sig-mixed-models/2008q2/000904.html
* https://stats.stackexchange.com/questions/22988/how-to-obtain-the-p-value-check-significance-of-an-effect-in-a-lme4-mixed-mode

If you really want to force the p-value without doing all of the work suggested in those links (`HDPInterval`, for example), you might find `lmerTest` useful.  I don't know if `broom.mixed` will tidy a `lmerTest` object, but it's probably your best shot.

**Comment by alexpghayes** [comment]
Thanks for the info! In that case I'm going to close this in favor of a potential feature request in `broom.mixed` from @IndrajeetPatil.
