### ISSUE TITLE
Glance behavior

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/broom#391]
Almost all glance methods have no additional arguments. The exceptions are:

- `glance.ergm`, `glance.ivreg`, `glance.stanreg`: have some logical arguments that add additional columns to the output if set to `TRUE`
- `glance.garch`: has a `method` argument that determines which test to apply to residuals
- `glance.survreg`: has a `conf.level` argument that appears to have been included mistakenly
- `glance.rowwise_df`: deprecated, so doesn't matter

Generally, I'm not a fan of `glance` methods having arguments. I think you should just get the same fixed information back every time, with `NA` in columns that are undefined and the option to `select` after the fact if `glance` has more than you want.

I'm proposing the following changes:
- have `glance.ergm`, `glance.ivreg`, `glance.stanreg` return all columns, all the time
- have `glance.garch` return p-values for both JB and BL tests all the time
- potentially changing the method signature of glance from `glance(x, ...)` to `glance(x)`

Mostly this will make it easier to test `glance` methods. @dgrtwo Thoughts?

**Comment by alexpghayes** [comment]
A somewhat related question is whether `glance` should return convergence information. I'm of that opinion that it shouldn't, and that `glance` should only return statistical measures. For Bayesian tidiers, I don't think MCMC diagnostics/summaries belong in `glance` either.

This is because I'd like to encourage a modelling workflow with distinct steps:

1. Did my model estimation procedure work?
2. How well does my model fit the data?

I think that `glance` should strictly do (2), and that there's space for a similar verb for (1) but that it isn't currently within the scope of `broom`. Definitely something to return to with `tidymodels` later on.

**Comment by dgrtwo** [comment]
Some glance methods like ergm look like they're considerably slower if the optional parameters are included, so IMO it's good to keep them optional: https://github.com/tidyverse/broom/blob/03b182d22c0570d1ad64ade67c8e41d1255e6502/R/ergm_tidiers.R#L129

**Comment by alexpghayes** [comment]
We also decided that returning convergence information is fine.
