### ISSUE TITLE
tidy.confint converts factor to numeric

### ISSUE THREAD

**Issue by dmenne** [tidyverse/broom#414]
My CRAN package breathtestcore gives an error with the release candidate 0.4.5.9000 of broom. 

    > coef_by_group(fit)
    Error in mutate_impl(.data, dots) :
      Evaluation error: non-numeric argument to mathematical function.
    Calls: coef_by_group ... <Anonymous> -> mutate -> mutate.tbl_df ->
mutate_impl
    Execution halted

This can be traced to a conversion of factors to numeric. See the example below: `lhs` should be a factor or a string, but is character(!) "1"

```
library(nlme)
library(multcomp)
#> Lade nötiges Paket: mvtnorm
#> Lade nötiges Paket: survival
#> Lade nötiges Paket: TH.data
#> Lade nötiges Paket: MASS
#> 
#> Attache Paket: 'TH.data'
#> The following object is masked from 'package:MASS':
#> 
#>     geyser
library(broom)
fit_lme = lme(distance~Sex, data = Orthodont, 
    random = ~1|Subject, subset = age == 14)

glh = glht(fit_lme, multcomp::mcp(Sex = "Tukey"))
tidy(confint(glh))
#> # A tibble: 1 x 5
#>   estimate conf.low conf.high lhs     rhs
#>      <dbl>    <dbl>     <dbl> <chr> <dbl>
#> 1    -3.38    -5.09     -1.66 1         0
```

**Comment by alexpghayes** [comment]
This is because the `data.frame` constructor in `tidy.glht` got replaced with a `tibble` constructor, and so the character vector of rownames is no longer coerced to `factor` by default with `stringsAsFactors = FALSE`. 

I just merged a PR so that reverts the multcomp tidiers to the old behavior where the `lhs` column is treated as a factor.

**Comment by dmenne** [comment]
It's a factor now, but somewhere on the road there was a conversion to integer.

```
# Github broom
# A tibble: 1 x 5
  estimate conf.low conf.high lhs     rhs
     <dbl>    <dbl>     <dbl> <fct> <dbl>
1    -3.38    -5.09     -1.66 1         0


#CRAN broom
           lhs rhs  estimate conf.low conf.high
1 Female - Male   0 -3.377841 -5.09195 -1.663732
```

**Comment by alexpghayes** [comment]
That was silly of me. Merged a new PR that brings behavior back in line with the CRAN version.

**Comment by dmenne** [comment]
Thanks, breathtestcore CRAN version now builds without problems with 0.4.5.9000.

Potentially related, but not relevant for breathtestcore: I tried confint_tidy instead of confint with the above, and got an error.

**Comment by alexpghayes** [comment]
Thanks. `confint_tidy` expects a `data.frame` with two columns, but the `confint.glht` objects are lists of ten items. I'll add some details about this to the `confint_tidy` documentation.
