### ISSUE TITLE
multiple lhs

### ISSUE THREAD

**Issue by matthieugomez** [tidyverse/broom#53]
felm supports multiple lhs. This estimates the model to each lhs, speeding up computations compared to an lapply loop. Should broom methods  support multiple lhs for felm  too? 
tidy would row_bind results for multiple lhs,  augment would create more columns (.fitted_nameofvar1, .fitted_nameofvar2 etc), and  glance would create a data.frame with nrow = length(lhs).

I want to write a pull request, but wanted to check  with you first.

**Comment by alexpghayes** [comment]
If `felm` fits a separate model for each response, I would prefer to not do this: tidiers should act on individual models rather than lists of models. Is the loss in computation speed using `tidy` together with `purrr::map_dfc` particularly painful?
