### ISSUE TITLE
Updated workflow figure or source

### ISSUE THREAD

**Issue by dhimmel** [tidyverse/broom#54]
@dgrtwo, I like your slide explaining the modern R workflow:

![broom_slides 001](https://cloud.githubusercontent.com/assets/1117703/8022886/1f857a9e-0ca4-11e5-8fc7-116fa01cd27d.jpg)

I would like to make a few modifications for an upcoming presentation:
- all black
- addition of `readr` and `readxl`

Do you have the source for the image, so I could make the changes? Or would you be interested in releasing the updated slide? Will attribute, of course.

**Comment by alexpghayes** [comment]
Hope you found an image and your presentation went well! Gonna close this since it isn't related to ongoing `broom` development.
