### ISSUE TITLE
Augment shouldn't drop NA rows

### ISSUE THREAD

**Issue by stefanfritsch** [tidyverse/broom#63]
Hi,

according to the help page augment does this:

> Given an R statistical model or other non-tidy object, add columns to the original dataset such as predictions, residuals and cluster assignments.

But even if you provide the original data, augment (at least for lm) will return the dataset _after_ `na.omit`, i.e. it is a reduced dataset without NA-rows.

I would prefer if augment really did augment the original data (with NA for the other rows) but it would be nice if you at least changed the documentation to make clear that it returns the reduced data. :)

Ciao,
Stefan

**Comment by gavinsimpson** [comment]
It might be better to have `augment()` respect the `na.action` requested by the user when the statistical model was fitted. Hence to achieve the behaviour you desire, the model would need to be fitted using the standard convention of `na.action = na.exclude`.

Where the model fitting function doesn't have an `na.action` argument, perhaps the `augment()` method could add an argument which would allow this `NA` preserving feature?

**Comment by stefanfritsch** [comment]
As I see it, if the parameter `data=dataset` is present, `augment` augments that dataset. So all rows of the input dataset should be present with new columns added.

That said, why not just add a column "na.action", that way the user has full control? Although in most cases that would just be an `is.na(fitted.values)`, wouldn't it? :)

**Comment by alexpghayes** [comment]
Dave and I talk about this earlier and we've decided to strictly enforce:

- `glance` returns a single row summarizing model level information
- `augment` returns a single row for each observation present in `data` or `newdata`, and if neither of those are present, for each observation present in the original training data. When there's missing data for a particular row, the `NA` will get propagated to `.fitted` and any other relevant columns.

**Comment by alexpghayes** [comment]
This has now been codified in the strict version of the `check_augment_function()` test. Very few of the strict tests are passing at the moment, but we're about to start making changes so that they do. Sorry about the delays on this, and thanks for your patience.
