### ISSUE TITLE
FR: tidier for car::vif

### ISSUE THREAD

**Issue by helix123** [tidyverse/broom#89]
A tidier for `car::vif(lm_model)` would be nice. Take care, the output depends on whether there is a factor in the lm model.

Example:

```
data(mtcars)
mtcars$gear <- factor(mtcars$gear)


lm_wo_fac <- lm(mpg ~ disp + hp,        data=mtcars)
lm_w_fac  <- lm(mpg ~ disp + hp + gear, data=mtcars)

vifs_wo_fac <- car::vif(lm_wo_fac)
vifs_w_fac <- car::vif(lm_w_fac)

class(vifs_wo_fac)
#> [1] "numeric"

class(vifs_w_fac)
#> [1] "matrix"


######### to be extracted by broom #######
vifs_wo_fac # directly
#>  disp    hp 
#> 2.671 2.671

# take both (in sep lines/columns)
vifs_w_fac[ , 1] # GVIF 
#>  disp    hp  gear 
#> 6.315 4.646 4.227

vifs_w_fac[ , 3] # adj. GVIF
#>  disp    hp  gear 
#> 2.513 2.156 1.434

# additional information
vifs_w_fac[ , 2] # df
#> disp   hp gear 
#>    1    1    2
```

**Comment by nutterb** [comment]
Just took a look at this, and I'm not sure it is feasible.

In the case of no factors, the resulting object has class `numeric`; it's a named atomic vector, but there's no way to identify that it contains VIFs.  

In the case of factors, the object has class `matrix`, and it would be possible to use the column names to determine if it is a `vif` matrix, but then you're left with an inconsistency for how the two forms of output are handled, and I don't find that very appealing.  

In the mean time, `tidy.numeric` and `tidy.matrix` (to be deprecated, but presumably replaced, see #364) perform the same function, but without explicitly identifying that the results are VIFs.  

If that isn't satisfactory, I think a better next step is to convince the maintainers of `car` to give the results of `car::vif` the `c("vif", "numeric")` and `c("vif", "matrix")` classes.

**Comment by alexpghayes** [comment]
Agreed, I think reaching out to the `car` maintainers is a good next step.

I was hoping that between `tibble::enframe` and `tibble::as_tibble` could step in for `tidy.numeric` and `tidy.matrix`, although now I wondering if remembering `enframe` vs `as_tibble` is cognitive load not worth introducing. Will talk to Dave about this.

```r
mtcars$gear <- factor(mtcars$gear)

lm_wo_fac <- lm(mpg ~ disp + hp,        data=mtcars)
lm_w_fac  <- lm(mpg ~ disp + hp + gear, data=mtcars)

vifs_wo_fac <- car::vif(lm_wo_fac)
vifs_w_fac <- car::vif(lm_w_fac)

tibble::enframe(vifs_wo_fac)
#> # A tibble: 2 x 2
#>   name  value
#>   <chr> <dbl>
#> 1 disp   2.67
#> 2 hp     2.67
tibble::as_tibble(vifs_w_fac)  
#> # A tibble: 3 x 3
#>    GVIF    Df `GVIF^(1/(2*Df))`
#>   <dbl> <dbl>             <dbl>
#> 1  6.32    1.              2.51
#> 2  4.65    1.              2.16
#> 3  4.23    2.              1.43
tibble::as_tibble(vifs_wo_fac)  # as_tibble on a numeric isn't great
#> # A tibble: 2 x 1
#>   value
#> * <dbl>
#> 1  2.67
#> 2  2.67
```

**Comment by alexpghayes** [comment]
Just emailed Dr. Fox since I couldn't find a place to submit feature requests on R Forge. 

If anybody understands how R Forge works, I'd love to steal a couple minutes of your time.

**Comment by alexpghayes** [comment]
Dr. Fox just got back to me and it looks like `car` won't give objects returned by `vif` a "vif" class. I agree with Benjamin that this puts the implementation into an unfortunate spot. For the moment, I'm going to close this and say that we won't implement `vif` tidiers based on that.
